### ISSUE TITLE
Graph pooling and LR

### ISSUE THREAD

**Issue by rongacmer** [jhonP-Li/ASD_GP_GCN#1]
Great job！I have a little problem about the Graph pooling and LR. Does this LR classifier directly classifies downsample datas or deal with the features after GCN model? Could you share you source code about the Graph pooling and LR.I am looking forward to your answer.Thanks!

**Comment by jhonP-Li** [comment]
Hi! The latest version on arXiv is dated, which overclaimed the performance of GP+LR and is different from the one we submitted for peer review. But GP+GCN works well. I will try to update the paper on arXiv these days. Thanks! @rongacmer
